In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("HousePricePrediction.csv")
df1=df.dropna()
# df.head(20)

In [3]:
x=df1.drop(columns= ["MSZoning", "LotConfig", "BldgType", "Exterior1st","SalePrice"])

In [4]:
x

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
0,0,60,8450,5,2003,2003,0.0,856.0
1,1,20,9600,8,1976,1976,0.0,1262.0
2,2,60,11250,5,2001,2002,0.0,920.0
3,3,70,9550,5,1915,1970,0.0,756.0
4,4,60,14260,5,2000,2000,0.0,1145.0
...,...,...,...,...,...,...,...,...
1455,1455,60,7917,5,1999,2000,0.0,953.0
1456,1456,20,13175,6,1978,1988,163.0,1542.0
1457,1457,70,9042,9,1941,2006,0.0,1152.0
1458,1458,20,9717,6,1950,1996,1029.0,1078.0
1459,1459,20,9937,6,1965,1965,290.0,1256.0

In [5]:
y=df1["SalePrice"]
y

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.2, random_state=42
)

In [7]:
y_train.head()

254     145000.0
1066    178000.0
638      85000.0
799     175000.0
380     127000.0
Name: SalePrice, dtype: float64

In [8]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [9]:
y_pred = model.predict(x_test)

In [10]:
y_pred

array([202557.9374021 , 233620.62893383, 120051.98714356, 134040.35280726,
       263271.0227539 , 127449.81819673, 186181.16276496, 157753.60118982,
       124602.09639799, 142621.77848951, 113476.10189918, 151218.99523931,
       115932.44986158, 247003.18467406, 197295.80982231, 190478.30449889,
       196683.48422666, 189193.45185039, 110146.07255011, 241062.78321246,
       170374.88570578, 198356.31967826, 191416.91209722, 173206.38788033,
       231725.43526673, 209131.11365407, 236915.33921068, 130252.93645157,
       196582.04197476, 237159.60189715, 117687.6123255 , 210615.52014226,
       215265.79562956, 143187.59054908, 261730.16884636, 165664.64614092,
       157704.00844856, 196667.88814434, 235795.62958066,  66883.8650627 ,
       107833.51848756, 197559.17116438, 150116.43011055, 295281.68156324,
       144092.2503778 ,  83683.07461516, 128169.53782967, 157409.64575552,
       273629.90177903, 134603.1080979 , 125944.91736627, 210552.38688086,
       116953.34271785, 212385.24519968, 196182.84126517, 265841.70907807,
       174629.94713716, 188160.59228909, 167152.82543625, 116161.4291717 ,
        80964.70036843, 180425.02131133, 221292.86730611, 256647.40077972,
       272928.39753314, 202120.41534498, 110126.75161905, 247188.09108399,
       189618.33051564, 180092.61758481,  98283.19918269, 139842.91653232,
       136115.97357928,  51259.91307056, 318377.47626115, 215924.07513364,
       229914.62502768, 218789.5140718 , 145271.08906059, 152845.50668495,
       167817.25903191,  89955.14443315, 146858.40711742, 114600.38276183,
       156630.87748927, 158696.99559954, 221264.63854634, 214597.52838436,
       196343.87195404, 195367.37548778, 192780.02295101, 137406.82768878,
       171726.11058676, 190808.27944617, 215674.77017743, 234880.3761576 ,
       169246.42882024, 178576.66696463, 247029.47549443, 178078.67165262,
       198137.40235183, 198996.9580622 , 262104.88634541, 161504.09430084,
       209708.19457004, 147643.05173747, 194907.16935247, 236044.71637106,
       193541.64079969, 163505.62957707,  50963.53674882, 171310.35836971,
       204958.97004057, 168555.89058474, 208191.78131563, 152847.09668469,
       174459.70207548, 147924.39809182,  99153.69668328, 360830.49891958,
       174549.58548131, 195808.44387027, 193071.05395616, 160374.71549367,
       215426.97505614, 148196.1991747 , 199957.12351628, 111822.96217534,
       217594.28058342, 157360.92543908, 191882.71616943, 276615.90255324,
       192756.06890075,  90433.41335408,  77693.55654438, 267143.64656904,
       270048.45064806, 159554.65226185, 252085.44932626, 321551.76091585,
       237744.26127339, 185732.58808375, 162243.55081392, 126681.521286  ,
       175843.49248811, 144987.59461869, 168333.65290986, 242809.62751351,
       188340.83611561,  84101.71672088,  91909.30009137, 126276.90327226,
       245260.6946565 , 156495.01205393, 107039.19442095, 159312.13547005,
       172717.95023683, 162838.31919135, 131940.1425572 , 159963.03551371,
       231311.60854011, 177200.05813136, 260778.49432493, 198650.84528087,
       114159.08319369, 199376.48477421, 196220.47437424, 249909.68508301,
       293091.82277952, 154572.87856606, 276590.16750164, 130312.22109696,
       111811.84592026, 142426.30774311, 250760.27820653,  72196.95501203,
       100303.31832289, 206200.44342575, 150646.74831559, 183072.10749218,
       216054.50229326,  96486.22027292, 164850.38840324, 148492.02570558,
       214324.64094522,  87815.12338779, 251427.61903927, 236415.37596776,
       239918.40518044, 122694.58938743, 139891.03528509, 133129.5735779 ,
       114958.98246173, 184418.61982257, 232545.14579355, 179717.37420017,
       225907.1544005 ,  79329.92761648, 197991.62586393,  96006.91132068,
       273402.39063319, 193136.26879372, 141709.34820581, 235329.10838075,
       230584.71226737, 144915.80455874, 206877.58324629, 161347.53620718,
       161472.76216314, 142287.30545708, 172469.24452534, 141830.12194442,
       137267.38039472, 180486.72010577, 228946.46206923, 255021.37594411,
       229457.99569013, 152927.83422147, 132467.90064597,  98874.28356275,
       158175.40313723, 236115.63975937, 206202.6929263 , 101713.20929681,
       246525.23756019, 205163.13119461,  81637.38550402, 146867.51476327,
       184124.36828854,  99133.26037477, 114534.82323296, 170174.72229621,
       134589.91106521, 161263.0053075 , 186163.1185466 , 143588.18957996,
       224808.28172803, 194189.81711905, 204042.17211531, 167500.40305675,
       149571.90456735, 182926.43400084, 213193.67912626, 247624.76473111,
       163828.69619732, 164647.84709641, 155456.88637449, 200926.29246041,
       179200.07434141, 103537.60453962, 206442.61620465, 149061.8951038 ,
       142338.94123498,  88840.63351567, 160842.40175006, 172279.36898173,
       159785.43565939, 142902.61940522, 172208.3736335 , 214905.7774514 ,
       285404.71996801, 191083.10397899, 150492.97154004, 230496.3123809 ,
       265742.12984093, 212925.73232331, 215495.32836984, 195914.99756025,
       137261.34288175, 157564.47127118, 295681.88005908, 216842.61024627,
       220326.45359958, 115075.8522018 ,  76440.37337303, 162845.53959973,
       205033.80072674, 279230.57507685, 252014.24991661, 127784.4435917 ,
       207752.12205327, 140801.23395379, 194877.44461591, 161125.77413579,
       266626.18627535, 201985.44082148, 205351.29109603, 164767.31696434,
       256685.61304714, 190273.45626308, 105910.15119776, 157498.15918877])

In [11]:
y_test

892     154500.0
1105    325000.0
413     115000.0
522     159000.0
1036    315500.0
          ...
479      89471.0
1361    260000.0
802     189000.0
651     108000.0
722     124500.0
Name: SalePrice, Length: 292, dtype: float64

In [12]:
from sklearn.metrics import r2_score
r2=r2_score(y_test, y_pred)
print("r-squared:",r2)

# adjusted r_squared
n=x_test.shape[0]
p=x_test.shape[1]

adjusted_r2 = 1-((1-r2)*(n-1)/(n-p-1))
print(adjusted_r2)

r-squared: 0.5749178852345282
0.5629014296934549

In [13]:
# Encoding
X=df1.drop(columns=["SalePrice","Exterior1st"])
Y=df1["SalePrice"]
X["House_age"] = 2026-X["YearBuilt"]
X["remod_age"]=2026-X["YearRemodAdd"]
X["Quality_area"] = X["OverallCond"]*X["LotArea"]
X["house_condn"] =  X["OverallCond"]*X["House_age"]
X=pd.get_dummies(X,columns=["LotConfig","MSZoning","BldgType"],drop_first=True,dtype=int)
X.sample(10)

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,House_age,remod_age,...,LotConfig_FR3,LotConfig_Inside,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE
1268,1268,50,14100,9,1935,1997,0.0,728.0,91,29,...,0,1,0,0,1,0,0,0,0,0
1105,1105,60,12256,5,1994,1995,0.0,1463.0,32,31,...,0,0,0,0,1,0,0,0,0,0
951,951,20,7800,5,1965,1965,0.0,828.0,61,61,...,0,0,0,1,0,0,0,0,0,0
180,180,160,2117,5,2000,2000,0.0,756.0,26,26,...,0,1,1,0,0,0,0,0,1,0
573,573,80,9967,5,2000,2000,0.0,384.0,26,26,...,0,1,0,0,1,0,0,0,0,0
769,769,60,53504,5,2003,2003,0.0,1650.0,23,23,...,0,0,0,0,1,0,0,0,0,0
566,566,60,11198,5,2005,2007,0.0,1122.0,21,19,...,0,1,0,0,1,0,0,0,0,0
1116,1116,80,7750,5,2002,2002,0.0,408.0,24,24,...,0,1,0,0,1,0,0,0,0,0
238,238,20,12030,5,2007,2007,0.0,1694.0,19,19,...,0,1,0,0,1,0,0,0,0,0
312,312,190,7800,7,1939,1950,0.0,793.0,87,76,...,0,1,0,0,0,1,1,0,0,0

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size = 0.2, random_state=42
)
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [15]:
Y_pred=model.predict(X_test)

In [16]:
srs=pd.Series(Y_pred)
srs.head()

0    168229.083649
1    258908.735198
2    111112.998168
3    139140.753134
4    257580.456482
dtype: float64

In [17]:
srs1=pd.Series(Y_test)
srs1.head()

892     154500.0
1105    325000.0
413     115000.0
522     159000.0
1036    315500.0
Name: SalePrice, dtype: float64

In [20]:
from sklearn.metrics import r2_score
r2=r2_score(Y_test, Y_pred)
print("r-squared:",r2)
y_train_pred = model.predict(X_train)
r2_train=r2_score(Y_train,y_train_pred)
print("R2_train",r2_train)
# adjusted r_squared
n=X_test.shape[0]
p=X_test.shape[1]

adjusted_r2 = 1-((1-r2)*(n-1)/(n-p-1))
print(adjusted_r2)

r-squared: 0.6276561057451815
R2_train 0.6074128667956897
0.5941869916548608